version: "3.9"

services:
  mongodb:
    image: mongo:8.0
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: >
      bash -c "
        if [ ! -f /data/db/.replica_set_initialized ]; then
          mongod --replSet rs0 --bind_ip_all --fork --logpath /var/log/mongodb.log &&
          sleep 3 &&
          echo 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"localhost:27017\" }]})' | mongosh &&
          touch /data/db/.replica_set_initialized &&
          tail -f /var/log/mongodb.log
        else
          mongod --replSet rs0 --bind_ip_all
        fi
      "
    environment:
      - MONGO_INITDB_DATABASE=dup
  
  redis:
    image: bitnami/redis:latest
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=     # 비워두고 싶으면 빈 값
      - ALLOW_EMPTY_PASSWORD=yes   # 빈 비밀번호 허용 (개발용)

volumes:
  mongo-data:
  redis-data:
