version: "3.9"

services:
  mongodb:
    image: mongo:8.0
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dup

volumes:
  mongo-data:
